In [1]:
%pip install "cbbpy"
%pip install "numpy<2"

Requirement already satisfied: cbbpy in c:\users\juan_\anaconda3\lib\site-packages (2.1.0)
Requirement already satisfied: pandas>=2.0.0 in c:\users\juan_\anaconda3\lib\site-packages (from cbbpy) (2.2.2)
Collecting numpy>=2.0.0 (from cbbpy)
  Using cached numpy-2.2.1-cp312-cp312-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: python-dateutil>=2.4.0 in c:\users\juan_\anaconda3\lib\site-packages (from cbbpy) (2.9.0.post0)
Requirement already satisfied: pytz>=2022.1 in c:\users\juan_\anaconda3\lib\site-packages (from cbbpy) (2024.1)
Requirement already satisfied: tqdm>=4.63.0 in c:\users\juan_\anaconda3\lib\site-packages (from cbbpy) (4.66.4)
Requirement already satisfied: lxml>=4.9.0 in c:\users\juan_\anaconda3\lib\site-packages (from cbbpy) (5.2.1)
Requirement already satisfied: joblib>=1.0.0 in c:\users\juan_\anaconda3\lib\site-packages (from cbbpy) (1.4.2)
Requirement already satisfied: beautifulsoup4>=4.11.0 in c:\users\juan_\anaconda3\lib\site-packages (from cbbpy) (4.12.3)
Requirement already satisfied: requests>=2.27.0 in c:\users\juan_\anaconda3\lib\site-packages (from cbbpy) (2.32.2)
Requirement already satisfied: rapidfuzz>=3.9.0 in c:\users\juan_\anaconda3\lib\site-packages (from cbbpy) (3.11.0)
Requirement already satisfied: platformdirs>=4.0.0 in c:\users\juan_\anaconda3\lib\site-packages (from cbbpy) (4.3.6)
Requirement already satisfied: soupsieve>1.2 in c:\users\juan_\anaconda3\lib\site-packages (from beautifulsoup4>=4.11.0->cbbpy) (2.5)
Requirement already satisfied: tzdata>=2022.7 in c:\users\juan_\anaconda3\lib\site-packages (from pandas>=2.0.0->cbbpy) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\juan_\anaconda3\lib\site-packages (from python-dateutil>=2.4.0->cbbpy) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\juan_\anaconda3\lib\site-packages (from requests>=2.27.0->cbbpy) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\juan_\anaconda3\lib\site-packages (from requests>=2.27.0->cbbpy) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\juan_\anaconda3\lib\site-packages (from requests>=2.27.0->cbbpy) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\juan_\anaconda3\lib\site-packages (from requests>=2.27.0->cbbpy) (2024.8.30)
Requirement already satisfied: colorama in c:\users\juan_\anaconda3\lib\site-packages (from tqdm>=4.63.0->cbbpy) (0.4.6)
Using cached numpy-2.2.1-cp312-cp312-win_amd64.whl (12.6 MB)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
Successfully installed numpy-2.2.1
Note: you may need to restart the kernel to use updated packages.

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\juan_\anaconda3\Lib\site-packages\~~mpy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\juan_\anaconda3\Lib\site-packages\~~mpy'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
contourpy 1.2.0 requires numpy<2.0,>=1.20, but you have numpy 2.2.1 which is incompatible.
numba 0.59.1 requires numpy<1.27,>=1.22, but you have numpy 2.2.1 which is incompatible.
pywavelets 1.5.0 requires numpy<2.0,>=1.22.4, but you have numpy 2.2.1 which is incompatible.
streamlit 1.32.0 requires numpy<2,>=1.19.3, but you have numpy 2.2.1 which is incompatible.

Collecting numpy<2
  Using cached numpy-1.26.4-cp312-cp312-win_amd64.whl.metadata (61 kB)
Using cached numpy-1.26.4-cp312-cp312-win_amd64.whl (15.5 MB)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.2.1
    Uninstalling numpy-2.2.1:
      Successfully uninstalled numpy-2.2.1
Successfully installed numpy-1.26.4
Note: you may need to restart the kernel to use updated packages.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cbbpy 2.1.0 requires numpy>=2.0.0, but you have numpy 1.26.4 which is incompatible.

In [3]:
import cbbpy.mens_scraper as s
import pytz
from datetime import datetime

In [4]:
s.get_game_info('401522202')

,game_id,game_status,home_team,home_id,home_rank,home_record,home_score,away_team,away_id,away_rank,...,game_day,game_time,game_loc,arena,arena_capacity,attendance,tv_network,referee_1,referee_2,referee_3
0,401522202,Final,UConn Huskies,41,4,31-8,76,San Diego State Aztecs,21,5,...,"April 03, 2023",06:20 PM PDT,"Houston, TX",NRG Stadium,NaN,72423.0,CBS,Ron Groover,Terry Oglesby,Keith Kimble

In [4]:
dir(s)

['Tuple',
 'Union',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_get_conference_schedule',
 '_get_current_season',
 '_get_game',
 '_get_game_boxscore',
 '_get_game_ids',
 '_get_game_info',
 '_get_game_pbp',
 '_get_games_conference',
 '_get_games_range',
 '_get_games_season',
 '_get_games_team',
 '_get_player_info',
 '_get_team_schedule',
 '_get_teams_from_conference',
 'datetime',
 'get_conference_schedule',
 'get_game',
 'get_game_boxscore',
 'get_game_ids',
 'get_game_info',
 'get_game_pbp',
 'get_games_conference',
 'get_games_range',
 'get_games_season',
 'get_games_team',
 'get_player_info',
 'get_team_schedule',
 'get_teams_from_conference',
 'pd']

In [21]:
class fbGame():
    def __init__(self, game_id: int, home_id: int, home_team: str, away_team: str, start_date: str):
        self.game_id = game_id
        self.home_id = home_id
        self.home_team = home_team
        self.away_team = away_team
        self.start_date = start_date

    def __str__(self):
        return f"game_id={self.game_id} home_id={self.home_id} home_team={self.home_team} away_team={self.away_team} start_date={self.start_date}"

In [6]:
game_list = s.get_team_schedule("Cincinnati", "2025")
game_list

,team,team_id,season,game_id,game_day,game_time,opponent,opponent_id,season_type,game_status,tv_network,game_result
0,Cincinnati,2132,2025,401715627,"November 04, 2024",04:00 PM PST,Arkansas-Pine Bluff Golden Lions,2029,Regular Season,Final,ESPN+,W 109-54
1,Cincinnati,2132,2025,401715628,"November 08, 2024",04:00 PM PST,Morehead State Eagles,2413,Regular Season,Final,ESPN+,W 83-56
2,Cincinnati,2132,2025,401715629,"November 15, 2024",04:00 PM PST,Nicholls Colonels,2447,Regular Season,Final,ESPN+,W 86-49
3,Cincinnati,2132,2025,401715630,"November 19, 2024",04:00 PM PST,Northern Kentucky Norse,94,Regular Season,Final,ESPN+,W 76-60
4,Cincinnati,2132,2025,401715631,"November 23, 2024",11:00 AM PST,Georgia Tech Yellow Jackets,59,Regular Season,Final,ESPN+,W 81-58
5,Cincinnati,2132,2025,401715632,"November 27, 2024",04:00 PM PST,Alabama State Hornets,2011,Regular Season,Final,ESPN+,W 77-59
6,Cincinnati,2132,2025,401715619,"December 03, 2024",03:30 PM PST,Villanova Wildcats,222,Regular Season,Final,FS1,L 60-68
7,Cincinnati,2132,2025,401715633,"December 08, 2024",11:00 AM PST,Howard Bison,47,Regular Season,Final,ESPN+,W 84-67
8,Cincinnati,2132,2025,401715626,"December 14, 2024",11:00 AM PST,Xavier Musketeers,2752,Regular Season,Final,ESPN+,W 68-65
9,Cincinnati,2132,2025,401715634,"December 20, 2024",05:30 PM PST,Dayton Flyers,2168,Regular Season,Final,ESPNU,W 66-59
10,Cincinnati,2132,2025,401715635,"December 22, 2024",01:00 PM PST,Grambling Tigers,2755,Regular Season,Final,ESPN+,W 84-49
11,Cincinnati,2132,2025,401725630,"December 30, 2024",04:00 PM PST,Kansas State Wildcats,2306,Regular Season,Final,CBSSN,L 67-70
12,Cincinnati,2132,2025,401725638,"January 04, 2025",11:30 AM PST,Arizona Wildcats,12,Regular Season,Final,ESPN2,L 67-72
13,Cincinnati,2132,2025,401725651,"January 07, 2025",05:00 PM PST,Baylor Bears,239,Regular Season,Scheduled,ESPN+,N/A
14,Cincinnati,2132,2025,401725656,"January 11, 2025",11:00 AM PST,Kansas Jayhawks,2305,Regular Season,Scheduled,ESPN+,N/A
15,Cincinnati,2132,2025,401725668,"January 15, 2025",06:00 PM PST,Colorado Buffaloes,38,Regular Season,Scheduled,ESPN+,N/A
16,Cincinnati,2132,2025,401725671,"January 18, 2025",11:00 AM PST,Arizona State Sun Devils,9,Regular Season,Scheduled,CBSSN,N/A
17,Cincinnati,2132,2025,401725682,"January 21, 2025",04:00 PM PST,Texas Tech Red Raiders,2641,Regular Season,Scheduled,,N/A
18,Cincinnati,2132,2025,401725692,"January 25, 2025",07:00 PM PST,BYU Cougars,252,Regular Season,Scheduled,ESPN2,N/A
19,Cincinnati,2132,2025,401725698,"January 28, 2025",07:00 PM PST,Utah Utes,254,Regular Season,Scheduled,CBSSN,N/A
20,Cincinnati,2132,2025,401725709,"February 02, 2025",11:00 AM PST,West Virginia Mountaineers,277,Regular Season,Scheduled,ESPN+,N/A
21,Cincinnati,2132,2025,401725716,"February 05, 2025",04:00 PM PST,UCF Knights,2116,Regular Season,Scheduled,CBSSN,N/A
22,Cincinnati,2132,2025,401725718,"February 08, 2025",03:00 PM PST,BYU Cougars,252,Regular Season,Scheduled,ESPN2,N/A
23,Cincinnati,2132,2025,401725729,"February 11, 2025",04:00 PM PST,Utah Utes,254,Regular Season,Scheduled,ESPN+,N/A
24,Cincinnati,2132,2025,401725741,"February 15, 2025",01:00 PM PST,Iowa State Cyclones,66,Regular Season,Scheduled,,N/A
25,Cincinnati,2132,2025,401725749,"February 19, 2025",04:00 PM PST,West Virginia Mountaineers,277,Regular Season,Scheduled,ESPN2,N/A
26,Cincinnati,2132,2025,401725753,"February 22, 2025",09:00 AM PST,TCU Horned Frogs,2628,Regular Season,Scheduled,,N/A
27,Cincinnati,2132,2025,401725762,"February 25, 2025",04:00 PM PST,Baylor Bears,239,Regular Season,Scheduled,ESPN2,N/A
28,Cincinnati,2132,2025,401725770,"March 01, 2025",01:30 PM PST,Houston Cougars,248,Regular Season,Scheduled,CBS,N/A
29,Cincinnati,2132,2025,401725780,"March 05, 2025",04:00 PM PST,Kansas State Wildcats,2306,Regular Season,Scheduled,ESPN+,N/A
30,Cincinnati,2132,2025,401725789,"March 08, 2025",12:00 PM PST,Oklahoma State Cowboys,197,Regular Season,Scheduled,ESPN+,N/A

In [9]:
player_info = s.get_player_info(5142608)
player_info

,player_id,first_name,last_name,jersey_number,pos,status,team,experience,height,weight,birthplace,date_of_birth
0,5142608,Jaiden,Glover,11,,Active,St. John's Red Storm,Freshman,"6' 4""",205 lbs,"Brooklyn, NY",

In [11]:
from classes import playerList
fullList = playerList()
fullList.populate()

In [24]:
player_team = player_info["team"].iloc[0]
player_team

"St. John's Red Storm"

In [39]:
test = '|'.join(player_team.split())
test

"St.|John's|Red|Storm"

In [35]:
filtered_df = fullList.__df__[fullList.__df__['team'].str.contains('|'.join(player_team.split()), na=False)]
filtered_df

,id,team,weight,height,jersey,year,position,name,school,color,alt_color,logos
1,5151354,Boise State,175.0,72.0,7.0,4.0,CB,A'Marion McCoy,Boise State,#0033a0,#fa4616,[http://a.espncdn.com/i/teamlogos/ncaa/500/68....
10,4567114,Alabama State,195.0,67.0,23.0,3.0,RB,A.J. Gates,Alabama State,#e9a900,#0a0a0a,[http://a.espncdn.com/i/teamlogos/ncaa/500/201...
11,5238620,Alabama State,0.0,0.0,-1.0,0.0,No Position Listed,A.J. Gates,Alabama State,#e9a900,#0a0a0a,[http://a.espncdn.com/i/teamlogos/ncaa/500/201...
12,4870721,Penn State,191.0,73.0,4.0,2.0,CB,A.J. Harris,Penn State,#041E42,#FFFFFF,[http://a.espncdn.com/i/teamlogos/ncaa/500/213...
20,5163591,Tarleton State,0.0,0.0,-1.0,0.0,No Position Listed,A.J. Sargent,Tarleton State,#152532,#c8caca,[http://a.espncdn.com/i/teamlogos/ncaa/500/262...
...,...,...,...,...,...,...,...,...,...,...,...,...
23072,4587870,Penn State,254.0,75.0,36.0,4.0,DE,Zuriah Fisher,Penn State,#041E42,#FFFFFF,[http://a.espncdn.com/i/teamlogos/ncaa/500/213...
23078,4683218,Jackson State,185.0,69.0,8.0,1.0,QB,Zy McDonald,Jackson State,#123297,#b5b7ba,[http://a.espncdn.com/i/teamlogos/ncaa/500/229...
23083,5078101,App State,190.0,70.0,28.0,1.0,S,Zyeir Gamble,App State,#ffcc00,#222222,[http://a.espncdn.com/i/teamlogos/ncaa/500/202...
23086,5109793,Morgan State,165.0,72.0,89.0,1.0,WR,Zyheem Coleman-Frazier,Morgan State,#014786,#f47937,[http://a.espncdn.com/i/teamlogos/ncaa/500/241...
23097,4683724,Arizona State,220.0,72.0,30.0,3.0,LB,Zyrus Fiaseu,Arizona State,#8e0c3a,#ffc72c,[http://a.espncdn.com/i/teamlogos/ncaa/500/9.p...

In [45]:
fullList.__df__

,id,team,weight,height,jersey,year,position,name,school,color,alt_color,logos
0,4840121,Liberty,195.0,70.0,29.0,3.0,S,A'Khori Jones,Liberty,#071740,#a61f21,[http://a.espncdn.com/i/teamlogos/ncaa/500/233...
1,5151354,Boise State,175.0,72.0,7.0,4.0,CB,A'Marion McCoy,Boise State,#0033a0,#fa4616,[http://a.espncdn.com/i/teamlogos/ncaa/500/68....
2,4918111,USC,220.0,72.0,22.0,1.0,RB,A'Marion Peterson,USC,#9e2237,#ffcc00,[http://a.espncdn.com/i/teamlogos/ncaa/500/30....
3,4899488,Oregon,330.0,75.0,52.0,2.0,DL,A'Mauri Washington,Oregon,#007030,#fee11a,[http://a.espncdn.com/i/teamlogos/ncaa/500/248...
4,5229547,Campbell,0.0,0.0,-1.0,0.0,No Position Listed,A'mari Wilson,Campbell,#152532,#c8caca,[http://a.espncdn.com/i/teamlogos/ncaa/500/209...
...,...,...,...,...,...,...,...,...,...,...,...,...
23093,4429114,Auburn,291.0,76.0,91.0,3.0,DL,Zykeivous Walker,Auburn,#002b5c,#f26522,[http://a.espncdn.com/i/teamlogos/ncaa/500/2.p...
23094,4917310,Louisiana,207.0,71.0,21.0,2.0,RB,Zylan Perry,Louisiana,#ce181e,#ffffff,[http://a.espncdn.com/i/teamlogos/ncaa/500/309...
23095,5081780,Houston Christian,240.0,74.0,53.0,4.0,DL,Zymir Cobbs,Houston Christian,#00539c,#c8caca,[http://a.espncdn.com/i/teamlogos/ncaa/500/227...
23096,5083591,Southern Utah,180.0,75.0,16.0,1.0,DB,Zyon Clark,Southern Utah,#c72026,#000000,[http://a.espncdn.com/i/teamlogos/ncaa/500/253...
23097,4683724,Arizona State,220.0,72.0,30.0,3.0,LB,Zyrus Fiaseu,Arizona State,#8e0c3a,#ffc72c,[http://a.espncdn.com/i/teamlogos/ncaa/500/9.p...

In [82]:
sched_df["datetime"] = game_list.apply(to_utc, axis=1)

now = datetime.now()

sched_df = sched_df.query(f'datetime <= "{now.strftime("%Y-%m-%d")}"')

sched_df.sort_values(by='datetime', inplace=True, ascending=False)

sched_df.reset_index(drop=True, inplace=True)

In [84]:
game_info = s.get_game_info(sched_df.iloc[0]["game_id"])

last_game = fbGame(game_id=row[1]["game_id"],
                       home_id=int(game_info["home_id"].iloc[0]),
                       home_team=game_info["home_team"].iloc[0],
                       away_team=game_info["away_team"].iloc[0],
                       start_date=final_date)

print(last_game)

game_id= home_id=2306 home_team=Kansas State Wildcats away_team=Cincinnati Bearcats start_date=2024-12-31T00:00:00.000Z

In [97]:
  sched_df = s.get_team_schedule("Cincinnati")
  
  sched_df["datetime"] = sched_df.apply(to_utc, axis=1)

  now = datetime.now()

  sched_df = sched_df.query(f'datetime > "{now.strftime("%Y-%m-%d")}"')

  sched_df.sort_values(by='datetime', inplace=True, ascending=True)

  sched_df.reset_index(drop=True, inplace=True)

  game_info = s.get_game_info(sched_df.iloc[0]["game_id"])

  next_game = fbGame(game_id=sched_df.iloc[0]["game_id"],
                        home_id=int(game_info["home_id"].iloc[0]),
                        home_team=game_info["home_team"].iloc[0],
                        away_team=game_info["away_team"].iloc[0],
                        start_date=sched_df.iloc[0]["datetime"])

  print(next_game)

game_id=401725638 home_id=2132 home_team=Cincinnati Bearcats away_team=Arizona Wildcats start_date=2025-01-04T19:30:00.000Z

In [50]:
s.get_game_boxscore(401725638)

,game_id,team,player,player_id,position,starter,min,fgm,fga,2pm,...,fta,oreb,dreb,reb,ast,stl,blk,to,pf,pts
0,401725638,Arizona Wildcats,T. Awaka,5105555,,True,14.0,1,3,1,...,0,2,2,4,0,0,0,2,3,2
1,401725638,Arizona Wildcats,T. Townsend,4702721,,True,24.0,2,7,2,...,2,0,4,4,0,0,0,0,2,6
2,401725638,Arizona Wildcats,A. Dell'Orso,5108141,,True,20.0,1,3,1,...,4,0,0,0,1,1,1,1,1,6
3,401725638,Arizona Wildcats,C. Love,4433144,,True,37.0,3,15,1,...,6,0,6,6,0,2,1,2,0,12
4,401725638,Arizona Wildcats,J. Bradley,4432737,,True,38.0,5,9,5,...,7,0,2,2,2,0,0,2,1,15
5,401725638,Arizona Wildcats,H. Veesaar,5105571,,False,26.0,3,5,3,...,2,3,5,8,4,2,2,0,3,8
6,401725638,Arizona Wildcats,C. Bryant,5061568,,False,15.0,5,5,2,...,2,1,3,4,0,0,1,1,4,14
7,401725638,Arizona Wildcats,KJ Lewis,5174952,,False,26.0,3,6,3,...,4,0,3,3,1,0,1,3,3,9
8,401725638,Arizona Wildcats,TEAM,TOTAL,TOTAL,False,NaN,23,53,18,...,27,8,26,34,8,5,6,12,17,72
9,401725638,Cincinnati Bearcats,A. Bandaogo,4703576,,True,28.0,2,3,2,...,4,4,5,9,0,0,2,1,3,5
10,401725638,Cincinnati Bearcats,D. Mitchell,5106283,,True,30.0,6,8,5,...,5,1,6,7,0,2,0,1,4,13
11,401725638,Cincinnati Bearcats,S. Lukosius,4897411,,True,29.0,2,6,1,...,4,0,3,3,3,0,0,3,0,9
12,401725638,Cincinnati Bearcats,J. James,5175033,,True,31.0,3,11,3,...,2,0,4,4,5,0,0,3,4,7
13,401725638,Cincinnati Bearcats,D. Skillings Jr.,5105811,,True,30.0,6,14,4,...,6,6,0,6,2,1,1,1,3,18
14,401725638,Cincinnati Bearcats,A. Page,5060696,,False,8.0,1,1,1,...,2,1,0,1,0,1,0,0,2,4
15,401725638,Cincinnati Bearcats,T. Betsey,4873141,,False,15.0,1,7,1,...,0,1,2,3,0,0,0,0,0,2
16,401725638,Cincinnati Bearcats,D. Thomas,5175032,,False,21.0,4,12,3,...,0,1,1,2,1,1,0,2,2,9
17,401725638,Cincinnati Bearcats,C. Hickman,4897447,,False,8.0,0,2,0,...,0,0,0,0,0,0,0,0,0,0
18,401725638,Cincinnati Bearcats,J. Reed,4838723,,False,0.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,401725638,Cincinnati Bearcats,TEAM,TOTAL,TOTAL,False,NaN,25,64,20,...,23,17,22,39,11,5,3,11,18,67

In [13]:
from utils.cbbpy_utils import _get_id_from_team, _get_team_map

In [5]:
_get_id_from_team("Cincinnati", datetime.now().year, "mens")[0]

2132

In [15]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

team_name = "Kentucky"


def get_bkb_players(team_name):
    team_id = _get_id_from_team(team_name, datetime.now().year, "mens")[0]
    
    url = f'https://www.espn.com/mens-college-basketball/team/roster/_/id/{team_id}/'
    headers = {'User-Agent': 'Mozilla/5.0'}
    response = requests.get(url, headers=headers)
    if response.status_code == 200:
        html_content = response.text
    else:
        print(f'Failed to retrieve the page. Status code: {response.status_code}')
    soup = BeautifulSoup(html_content, 'html.parser')
    roster_table = soup.find('table', {'class': 'Table'})
    if roster_table:
        players = []
        for row in roster_table.find_all('tr')[1:]:  # Skip the header row
            cols = row.find_all('td')
            if len(cols) >= 4:
                id_html = cols[0].find('a')
                raw_name = cols[1].text.strip()
                num_start = 0
                jers_shown = False
                for i, char in enumerate(raw_name):
                    if char.isdigit():
                        num_start = i
                        jers_shown = True
                        break
                if jers_shown:
                    name = raw_name[:num_start]
                    number = raw_name[num_start:]
                else:
                    name = raw_name
                    number = -1
                position = cols[2].text.strip()
                raw_height = cols[3].text.strip()
                height = (int(raw_height[:raw_height.find("'")].replace("-", "0"))*12
                          +int(raw_height[raw_height.find("'")+1:raw_height.find("'")+4].replace('"', '').replace("--", "-1").replace("-", "-1")))
                weight = cols[4].text.strip().replace(" lbs", "").replace("--", "-1")
                pl_class = cols[5].text.strip()
                match pl_class:
                    case 'FR':
                        year = 1
                    case 'SO':
                        year = 2
                    case 'JR':
                        year = 3
                    case 'SR':
                        year = 4
                    case _:
                        year = 0
    
                # Extract player ID from the href attribute of the link
                player_id = None
                if id_html and 'href' in id_html.attrs:
                    href = id_html['href']
                    # Extract the numeric player ID from the href (e.g., '/mens-college-basketball/player/_/id/12345/')
                    player_id = href.split('/')[-2] if 'player/_/id/' in href else None
                players.append({
                    'id': player_id,
                    'jersey': int(number),
                    'name': name,
                    'position': position,
                    'height': height,
                    'weight': int(weight),
                    'year' : year
                })
    else:
        print('Roster table not found.')
    
    return pd.DataFrame(players)

In [17]:
def get_bkb_players_by_id(team_id, team_name):
    
    url = f'https://www.espn.com/mens-college-basketball/team/roster/_/id/{team_id}/'
    headers = {'User-Agent': 'Mozilla/5.0'}
    response = requests.get(url, headers=headers)
    if response.status_code == 200:
        html_content = response.text
    else:
        print(f'Failed to retrieve the page. Status code: {response.status_code}, team: {team_name}')
    soup = BeautifulSoup(html_content, 'html.parser')
    roster_table = soup.find('table', {'class': 'Table'})
    found_roster = False
    if roster_table:
        found_roster = True
        players = []
        for row in roster_table.find_all('tr')[1:]:  # Skip the header row
            cols = row.find_all('td')
            if len(cols) >= 4:
                id_html = cols[0].find('a')
                raw_name = cols[1].text.strip()
                num_start = 0
                jers_shown = False
                for i, char in enumerate(raw_name):
                    if char.isdigit():
                        num_start = i
                        jers_shown = True
                        break
                if jers_shown:
                    name = raw_name[:num_start]
                    number = raw_name[num_start:]
                else:
                    name = raw_name
                    number = -1
                position = cols[2].text.strip()
                raw_height = cols[3].text.strip()
                height = (int(raw_height[:raw_height.find("'")].replace("-", "0"))*12
                          +int(raw_height[raw_height.find("'")+1:raw_height.find("'")+4].replace('"', '').replace("--", "-1").replace("-", "-1")))
                weight = cols[4].text.strip().replace(" lbs", "").replace("--", "-1")
                pl_class = cols[5].text.strip()
                match pl_class:
                    case 'FR':
                        year = 1
                    case 'SO':
                        year = 2
                    case 'JR':
                        year = 3
                    case 'SR':
                        year = 4
                    case _:
                        year = 0
    
                # Extract player ID from the href attribute of the link
                player_id = None
                if id_html and 'href' in id_html.attrs:
                    href = id_html['href']
                    # Extract the numeric player ID from the href (e.g., '/mens-college-basketball/player/_/id/12345/')
                    player_id = href.split('/')[-2] if 'player/_/id/' in href else None
                players.append({
                    'id': player_id,
                    'jersey': int(number),
                    'name': name,
                    'position': position,
                    'height': height,
                    'weight': int(weight),
                    'year' : year,
                    'team' : team_name
                })
    else:
        print(f'Roster table not found, id = {team_id}')
    if found_roster:
        return pd.DataFrame(players)
    else: 
        return pd.DataFrame(columns=["id","jersey","name","position","height","weight","year","team"])

In [26]:
search_results

[]

In [20]:
team_info = _get_team_map("mens")[['id', 'location']].drop_duplicates()

team_list = list(team_info.itertuples(index=False, name=None))

players_df = pd.DataFrame(columns=["id","jersey","name","position","height","weight","year", "team"])

for id, name in team_list:
    curr = get_bkb_players_by_id(id, name)
    players_df = pd.concat([players_df, curr])
    players_df.reset_index(drop=True, inplace=True)

players_df.drop_duplicates(inplace=True)
players_df

Roster table not found, id = 2597
Roster table not found, id = 2417

,id,jersey,name,position,height,weight,year,team
0,4702115,1,Cam Bryant,F,79,205,4,Mercer
1,5243237,24,Braeden Carlsen,G,76,200,1,Mercer
2,5108878,14,TJ Grant,F,77,210,3,Mercer
3,4702103,6,Alex Holt,F,80,220,4,Mercer
4,5243234,3,Tyler Johnson,G,74,180,4,Mercer
...,...,...,...,...,...,...,...,...
5933,5243384,23,Charles McClennahan Jr.,F,80,210,3,Mercyhurst
5934,4709436,31,Jeff Planutis,F,78,215,4,Mercyhurst
5935,4702990,22,Shemar Rathan-Mayes,G,70,175,4,Mercyhurst
5936,5243385,32,Aidan Reichert,F,76,215,4,Mercyhurst
5937,5243386,34,James Thomas,F,78,230,3,Mercyhurst

In [134]:


def add_details_to_row(row):
    team = row["team"]
    curr_deets = details.query(f'team == "{team}"')
    if curr_deets.empty:
        row["color"] = '#152532'
        row["alt_color"] = '#c8caca'
        row["logos"] = "[https://drive.google.com/drive-viewer/AKGpihaYb1Y1nEr1OtOU6402JARAiPa-6Moru1jZuz7Br_szY168Xq1E7MkBQHN6cMihX7ULokKQfUyKQP-JYZ05J_cdQ6JL1EKAPaM=w1920-h912]"
    else:   
        row["color"] = curr_deets["color"].iloc[0]
        row["alt_color"] = curr_deets["alt_color"].iloc[0]
        row["logos"] = curr_deets["logos"].iloc[0]

    return row

In [17]:
details  = fullList.__df__[['team', 'color', 'alt_color', 'logos']].drop_duplicates(subset=['team'])

columns = list(details.columns) + list(players_df.columns)
columns = columns[0:-1]

details_df = players_df = pd.DataFrame(columns=columns)
details_df

Empty DataFrame
Columns: [team, color, alt_color, logos, id, jersey, name, position, height, weight, year]
Index: []

In [43]:
details  = fullList.__df__[['team', 'color', 'alt_color', 'logos']].drop_duplicates(subset=['team'])

columns = list(details.columns) + list(players_df.columns)
columns = columns[0:-1]

details_df = pd.DataFrame(columns=columns)
for index, row in players_df.iterrows():
    curr_deets = details.query(f'team == "{row["team"]}"')
    if curr_deets.empty:
        curr_col = '#152532'
        curr_alt = '#c8caca'
        curr_log = "[https://drive.google.com/drive-viewer/AKGpihaYb1Y1nEr1OtOU6402JARAiPa-6Moru1jZuz7Br_szY168Xq1E7MkBQHN6cMihX7ULokKQfUyKQP-JYZ05J_cdQ6JL1EKAPaM=w1920-h912]"
    else:   
        curr_col = curr_deets["color"].iloc[0]
        curr_alt = curr_deets["alt_color"].iloc[0]
        curr_log = curr_deets["logos"].iloc[0]
    curr = {"team": row["team"],
            "color" : curr_col,
            "alt_color": curr_alt,
            "logos": curr_log,
            "id" : row["id"],
            "jersey" : row["jersey"],
            "name" : row["name"],
            "position" : row["position"],
            "height" : row["height"],
            "weight" : row["weight"],
            "year" : row["year"]
           }
    details_df.loc[len(details_df)] = curr
    #break
details_df

,team,color,alt_color,logos,id,jersey,name,position,height,weight,year
0,Mercer,#ff7f29,#080808,[http://a.espncdn.com/i/teamlogos/ncaa/500/238...,4702115.0,1,Cam Bryant,F,79,205,4
1,Mercer,#ff7f29,#080808,[http://a.espncdn.com/i/teamlogos/ncaa/500/238...,5243237.0,24,Braeden Carlsen,G,76,200,1
2,Mercer,#ff7f29,#080808,[http://a.espncdn.com/i/teamlogos/ncaa/500/238...,5108878.0,14,TJ Grant,F,77,210,3
3,Mercer,#ff7f29,#080808,[http://a.espncdn.com/i/teamlogos/ncaa/500/238...,4702103.0,6,Alex Holt,F,80,220,4
4,Mercer,#ff7f29,#080808,[http://a.espncdn.com/i/teamlogos/ncaa/500/238...,5243234.0,3,Tyler Johnson,G,74,180,4
...,...,...,...,...,...,...,...,...,...,...,...
5933,Mercyhurst,#152532,#c8caca,[http://a.espncdn.com/i/teamlogos/ncaa/500/238...,5243384.0,23,Charles McClennahan Jr.,F,80,210,3
5934,Mercyhurst,#152532,#c8caca,[http://a.espncdn.com/i/teamlogos/ncaa/500/238...,4709436.0,31,Jeff Planutis,F,78,215,4
5935,Mercyhurst,#152532,#c8caca,[http://a.espncdn.com/i/teamlogos/ncaa/500/238...,4702990.0,22,Shemar Rathan-Mayes,G,70,175,4
5936,Mercyhurst,#152532,#c8caca,[http://a.espncdn.com/i/teamlogos/ncaa/500/238...,5243385.0,32,Aidan Reichert,F,76,215,4
5937,Mercyhurst,#152532,#c8caca,[http://a.espncdn.com/i/teamlogos/ncaa/500/238...,5243386.0,34,James Thomas,F,78,230,3

In [13]:
fullList.populate()

In [29]:
players_df

Empty DataFrame
Columns: [team, color, alt_color, logos, team, color, alt_color, logos, team, color, alt_color, logos, team, color, alt_color, logos, id, jersey, name, position]
Index: []

In [14]:
fullList.__df__

,id,team,weight,height,jersey,year,position,name,school,color,alt_color,logos
0,4840121,Liberty,195.0,70.0,29.0,3.0,S,A'Khori Jones,Liberty,#071740,#a61f21,[http://a.espncdn.com/i/teamlogos/ncaa/500/233...
1,5151354,Boise State,175.0,72.0,7.0,4.0,CB,A'Marion McCoy,Boise State,#0033a0,#fa4616,[http://a.espncdn.com/i/teamlogos/ncaa/500/68....
2,4918111,USC,220.0,72.0,22.0,1.0,RB,A'Marion Peterson,USC,#9e2237,#ffcc00,[http://a.espncdn.com/i/teamlogos/ncaa/500/30....
3,4899488,Oregon,330.0,75.0,52.0,2.0,DL,A'Mauri Washington,Oregon,#007030,#fee11a,[http://a.espncdn.com/i/teamlogos/ncaa/500/248...
4,5229547,Campbell,0.0,0.0,-1.0,0.0,No Position Listed,A'mari Wilson,Campbell,#152532,#c8caca,[http://a.espncdn.com/i/teamlogos/ncaa/500/209...
...,...,...,...,...,...,...,...,...,...,...,...,...
23093,4429114,Auburn,291.0,76.0,91.0,3.0,DL,Zykeivous Walker,Auburn,#002b5c,#f26522,[http://a.espncdn.com/i/teamlogos/ncaa/500/2.p...
23094,4917310,Louisiana,207.0,71.0,21.0,2.0,RB,Zylan Perry,Louisiana,#ce181e,#ffffff,[http://a.espncdn.com/i/teamlogos/ncaa/500/309...
23095,5081780,Houston Christian,240.0,74.0,53.0,4.0,DL,Zymir Cobbs,Houston Christian,#00539c,#c8caca,[http://a.espncdn.com/i/teamlogos/ncaa/500/227...
23096,5083591,Southern Utah,180.0,75.0,16.0,1.0,DB,Zyon Clark,Southern Utah,#c72026,#000000,[http://a.espncdn.com/i/teamlogos/ncaa/500/253...
23097,4683724,Arizona State,220.0,72.0,30.0,3.0,LB,Zyrus Fiaseu,Arizona State,#8e0c3a,#ffc72c,[http://a.espncdn.com/i/teamlogos/ncaa/500/9.p...

In [154]:
import os

In [45]:
details_df.to_csv(f"{os.getcwd()}/cache/bkb_players.csv")

,id,jersey,name,position,height,weight,year,team
0,4702115.0,1,Cam Bryant,F,79,205,4,Mercer
1,5243237.0,24,Braeden Carlsen,G,76,200,1,Mercer
2,5108878.0,14,TJ Grant,F,77,210,3,Mercer
3,4702103.0,6,Alex Holt,F,80,220,4,Mercer
4,5243234.0,3,Tyler Johnson,G,74,180,4,Mercer
...,...,...,...,...,...,...,...,...
5933,5243384.0,23,Charles McClennahan Jr.,F,80,210,3,Mercyhurst
5934,4709436.0,31,Jeff Planutis,F,78,215,4,Mercyhurst
5935,4702990.0,22,Shemar Rathan-Mayes,G,70,175,4,Mercyhurst
5936,5243385.0,32,Aidan Reichert,F,76,215,4,Mercyhurst
5937,5243386.0,34,James Thomas,F,78,230,3,Mercyhurst

In [31]:
from classes import bkbPlayers
def get_bkb_last_game_id(team):
  sched_df = s.get_team_schedule(team)
  
  sched_df["datetime"] = sched_df.apply(bkbPlayers.to_utc, axis=1)

  now = datetime.now()

  sched_df = sched_df.query(f'datetime <= "{now.strftime("%Y-%m-%d")}"')

  sched_df.sort_values(by='datetime', inplace=True, ascending=False)

  sched_df.reset_index(drop=True, inplace=True)

  return int(sched_df.iloc[0]["game_id"])

In [33]:

bkbList = bkbPlayers(fullList)
test = get_bkb_last_game_id("cincinnati")
test

C:\Users\juan_\AppData\Local\Temp\ipykernel_17728\53365276.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sched_df.sort_values(by='datetime', inplace=True, ascending=False)

401725638

In [93]:
s.get_game_boxscore(401725638)

,game_id,team,player,player_id,position,starter,min,fgm,fga,2pm,...,fta,oreb,dreb,reb,ast,stl,blk,to,pf,pts
0,401725638,Arizona Wildcats,T. Awaka,5105555,,True,14.0,1,3,1,...,0,2,2,4,0,0,0,2,3,2
1,401725638,Arizona Wildcats,T. Townsend,4702721,,True,24.0,2,7,2,...,2,0,4,4,0,0,0,0,2,6
2,401725638,Arizona Wildcats,A. Dell'Orso,5108141,,True,20.0,1,3,1,...,4,0,0,0,1,1,1,1,1,6
3,401725638,Arizona Wildcats,C. Love,4433144,,True,37.0,3,15,1,...,6,0,6,6,0,2,1,2,0,12
4,401725638,Arizona Wildcats,J. Bradley,4432737,,True,38.0,5,9,5,...,7,0,2,2,2,0,0,2,1,15
5,401725638,Arizona Wildcats,H. Veesaar,5105571,,False,26.0,3,5,3,...,2,3,5,8,4,2,2,0,3,8
6,401725638,Arizona Wildcats,C. Bryant,5061568,,False,15.0,5,5,2,...,2,1,3,4,0,0,1,1,4,14
7,401725638,Arizona Wildcats,KJ Lewis,5174952,,False,26.0,3,6,3,...,4,0,3,3,1,0,1,3,3,9
8,401725638,Arizona Wildcats,TEAM,TOTAL,TOTAL,False,NaN,23,53,18,...,27,8,26,34,8,5,6,12,17,72
9,401725638,Cincinnati Bearcats,A. Bandaogo,4703576,,True,28.0,2,3,2,...,4,4,5,9,0,0,2,1,3,5
10,401725638,Cincinnati Bearcats,D. Mitchell,5106283,,True,30.0,6,8,5,...,5,1,6,7,0,2,0,1,4,13
11,401725638,Cincinnati Bearcats,S. Lukosius,4897411,,True,29.0,2,6,1,...,4,0,3,3,3,0,0,3,0,9
12,401725638,Cincinnati Bearcats,J. James,5175033,,True,31.0,3,11,3,...,2,0,4,4,5,0,0,3,4,7
13,401725638,Cincinnati Bearcats,D. Skillings Jr.,5105811,,True,30.0,6,14,4,...,6,6,0,6,2,1,1,1,3,18
14,401725638,Cincinnati Bearcats,A. Page,5060696,,False,8.0,1,1,1,...,2,1,0,1,0,1,0,0,2,4
15,401725638,Cincinnati Bearcats,T. Betsey,4873141,,False,15.0,1,7,1,...,0,1,2,3,0,0,0,0,0,2
16,401725638,Cincinnati Bearcats,D. Thomas,5175032,,False,21.0,4,12,3,...,0,1,1,2,1,1,0,2,2,9
17,401725638,Cincinnati Bearcats,C. Hickman,4897447,,False,8.0,0,2,0,...,0,0,0,0,0,0,0,0,0,0
18,401725638,Cincinnati Bearcats,J. Reed,4838723,,False,0.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,401725638,Cincinnati Bearcats,TEAM,TOTAL,TOTAL,False,NaN,25,64,20,...,23,17,22,39,11,5,3,11,18,67

In [ ]:
team_list = bkbList.df["team"].unique()
team_list

last_game_list = []

for team in team_list:
    last_game_list.append(get_bkb_last_game_id(team))

In [ ]:
starters = []

for game in last_game_list:
    box_df = s.get_game_boxscore(game)
    
    curr_starters = box_df[box_df['starter'] == True]["player_id"].astype('int').values.tolist()

    starters = starters + curr_starters

starters

In [145]:
starters_df = bkbList.df[bkbList.df['id'].isin(starters)]
starters_df

,Unnamed: 0,team,color,alt_color,logos,id,jersey,name,position,height,weight,year
0,0,Mercer,#ff7f29,#080808,['http://a.espncdn.com/i/teamlogos/ncaa/500/23...,4702115.0,1,Cam Bryant,F,79,205,4
3,3,Mercer,#ff7f29,#080808,['http://a.espncdn.com/i/teamlogos/ncaa/500/23...,4702103.0,6,Alex Holt,F,80,220,4
4,4,Mercer,#ff7f29,#080808,['http://a.espncdn.com/i/teamlogos/ncaa/500/23...,5243234.0,3,Tyler Johnson,G,74,180,4
11,11,Mercer,#ff7f29,#080808,['http://a.espncdn.com/i/teamlogos/ncaa/500/23...,5175704.0,4,Ahmad Robinson,G,70,175,4
12,12,Mercer,#ff7f29,#080808,['http://a.espncdn.com/i/teamlogos/ncaa/500/23...,5243236.0,11,Brady Shoulders,G,78,200,1
...,...,...,...,...,...,...,...,...,...,...,...,...
5924,5924,Mercyhurst,#152532,#c8caca,['http://a.espncdn.com/i/teamlogos/ncaa/500/23...,4898243.0,4,Bernie Blunt III,G,71,180,4
5929,5929,Mercyhurst,#152532,#c8caca,['http://a.espncdn.com/i/teamlogos/ncaa/500/23...,5243383.0,21,Max Jusianiec,F,79,210,3
5934,5934,Mercyhurst,#152532,#c8caca,['http://a.espncdn.com/i/teamlogos/ncaa/500/23...,4709436.0,31,Jeff Planutis,F,78,215,4
5935,5935,Mercyhurst,#152532,#c8caca,['http://a.espncdn.com/i/teamlogos/ncaa/500/23...,4702990.0,22,Shemar Rathan-Mayes,G,70,175,4
5936,5936,Mercyhurst,#152532,#c8caca,['http://a.espncdn.com/i/teamlogos/ncaa/500/23...,5243385.0,32,Aidan Reichert,F,76,215,4

In [152]:
from classes import firstStringList

fs = firstStringList(fullList)
fs.populate()
fs.__df__

C:\Users\juan_\Desktop\All code i guess\Python\SeniorDesign\server\classes.py:225: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  first_stringers = pd.concat([first_stringers, curr])

,id,team,weight,height,jersey,year,position,name,school,color,alt_color,logos
0,4433971,Syracuse,220.0,75.0,6.0,4.0,QB,Kyle McCord,Syracuse,#ff6500,#000e54,[http://a.espncdn.com/i/teamlogos/ncaa/500/183...
1,4911851,Syracuse,201.0,72.0,1.0,3.0,RB,LeQuint Allen,Syracuse,#ff6500,#000e54,[http://a.espncdn.com/i/teamlogos/ncaa/500/183...
2,4575862,Syracuse,184.0,72.0,2.0,3.0,WR,Trebor Pena,Syracuse,#ff6500,#000e54,[http://a.espncdn.com/i/teamlogos/ncaa/500/183...
3,4595342,Syracuse,236.0,77.0,19.0,3.0,TE,Oronde Gadsden II,Syracuse,#ff6500,#000e54,[http://a.espncdn.com/i/teamlogos/ncaa/500/183...
4,4694399,Syracuse,179.0,71.0,96.0,3.0,PK,Jackson Kennedy,Syracuse,#ff6500,#000e54,[http://a.espncdn.com/i/teamlogos/ncaa/500/183...
...,...,...,...,...,...,...,...,...,...,...,...,...
665,5223107,Air Force,195.0,72.0,10.0,2.0,QB,Quentin Hayes,Air Force,#004a7b,#ffffff,[http://a.espncdn.com/i/teamlogos/ncaa/500/200...
666,5151906,Air Force,215.0,72.0,5.0,3.0,RB,Dylan Carson,Air Force,#004a7b,#ffffff,[http://a.espncdn.com/i/teamlogos/ncaa/500/200...
667,5085137,Air Force,185.0,68.0,21.0,4.0,WR,Cade Harris,Air Force,#004a7b,#ffffff,[http://a.espncdn.com/i/teamlogos/ncaa/500/200...
668,5151942,Air Force,235.0,77.0,88.0,3.0,TE,Bruin Fleischmann,Air Force,#004a7b,#ffffff,[http://a.espncdn.com/i/teamlogos/ncaa/500/200...
669,4887281,Air Force,190.0,72.0,43.0,4.0,PK,Matthew Dapore,Air Force,#004a7b,#ffffff,[http://a.espncdn.com/i/teamlogos/ncaa/500/200...

In [156]:
fs.__df__.to_csv(f"{os.getcwd()}/cache/fb/first_string.csv")

In [158]:
starters_df.to_csv(f"{os.getcwd()}/cache/bkb/first_string.csv")

In [47]:
s.get_game_boxscore(401522202).columns

Index(['game_id', 'team', 'player', 'player_id', 'position', 'starter', 'min',
       'fgm', 'fga', '2pm', '2pa', '3pm', '3pa', 'ftm', 'fta', 'oreb', 'dreb',
       'reb', 'ast', 'stl', 'blk', 'to', 'pf', 'pts'],
      dtype='object')

In [60]:
s.get_game_boxscore(401522202)[['player_id', '3pm', '2pm',
                                'ftm', 'reb', 'ast', 'blk', 'stl', 'to']]

   player_id  3pm  2pm  ftm  reb  ast  blk  stl  to
0    4431786    1    2    7    4    1    0    0   0
1    4397371    0    0    1    6    0    1    2   1
2    4702011    1    4    2    3    1    0    3   2
3    4433183    3    2    0    4    2    1    1   4
4    4397049    0    2    4    3    1    0    1   1
5    4897531    0    0    0    0    0    0    0   0
6    4870565    0    0    0    0    0    0    0   0
7    4431879    0    0    0    0    0    0    0   0
8    4397368    0    0    0    4    1    0    0   1
9    4397237    0    3    1    4    1    0    0   2
10   4702719    0    0    0    3    0    0    0   0
11   4593084    0    0    0    0    0    0    0   0
12   4278704    1    0    0    2    0    0    0   1
13     TOTAL    6   13   15   34    7    2    7  12
14   4917149    1    0    2    5    0    3    0   2
15   4702023    0    5    7   10    1    1    0   0
16   4683750    2    3    4    4    0    1    1   1
17   4592965    1    4    8   10    4    0    2   5
18   4432190    0    1    1    3    6    0    2   2
19   4592905    0    0    0    0    0    0    0   0
20   5105566    0    0    0    0    0    0    0   0
21   5105565    0    2    0    3    1    1    2   1
22   4683752    0    0    0    0    0    0    0   0
23   4702022    0    0    0    1    0    0    0   0
24   4433160    0    0    0    0    0    0    0   0
25   4432934    0    2    2    3    0    0    0   0
26   4280214    2    0    0    1    1    0    1   2
27     TOTAL    6   17   24   40   13    6    8  13

In [75]:
bkbList.df.query("team == 'Cincinnati'")

,Unnamed: 0,team,color,alt_color,logos,id,jersey,name,position,height,weight,year
1887,1887,Cincinnati,#E00122,#000000,['http://a.espncdn.com/i/teamlogos/ncaa/500/21...,4897054.0,11,CJ Anthony,G,72,195,4
1888,1888,Cincinnati,#E00122,#000000,['http://a.espncdn.com/i/teamlogos/ncaa/500/21...,4703576.0,55,Aziz Bandaogo,F,84,235,4
1889,1889,Cincinnati,#E00122,#000000,['http://a.espncdn.com/i/teamlogos/ncaa/500/21...,4873141.0,14,Tyler Betsey,F,80,225,1
1890,1890,Cincinnati,#E00122,#000000,['http://a.espncdn.com/i/teamlogos/ncaa/500/21...,5240256.0,65,Halvine Dzellat,F,82,225,1
1891,1891,Cincinnati,#E00122,#000000,['http://a.espncdn.com/i/teamlogos/ncaa/500/21...,4397032.0,5,CJ Fredrick Jr.,G,75,185,4
1892,1892,Cincinnati,#E00122,#000000,['http://a.espncdn.com/i/teamlogos/ncaa/500/21...,4683765.0,3,Rayvon Griffith,G,78,210,1
1893,1893,Cincinnati,#E00122,#000000,['http://a.espncdn.com/i/teamlogos/ncaa/500/21...,4897447.0,8,Connor Hickman,G,75,200,4
1894,1894,Cincinnati,#E00122,#000000,['http://a.espncdn.com/i/teamlogos/ncaa/500/21...,5175033.0,2,Jizzle James,G,75,205,2
1895,1895,Cincinnati,#E00122,#000000,['http://a.espncdn.com/i/teamlogos/ncaa/500/21...,4897411.0,41,Simas Lukosius,G,80,225,4
1896,1896,Cincinnati,#E00122,#000000,['http://a.espncdn.com/i/teamlogos/ncaa/500/21...,4873163.0,24,Tyler McKinley,F,81,240,1
1897,1897,Cincinnati,#E00122,#000000,['http://a.espncdn.com/i/teamlogos/ncaa/500/21...,5106283.0,23,Dillon Mitchell,F,80,210,3
1898,1898,Cincinnati,#E00122,#000000,['http://a.espncdn.com/i/teamlogos/ncaa/500/21...,5060696.0,22,Arrinten Page,F,83,240,2
1899,1899,Cincinnati,#E00122,#000000,['http://a.espncdn.com/i/teamlogos/ncaa/500/21...,4838723.0,10,Josh Reed,G,79,220,3
1900,1900,Cincinnati,#E00122,#000000,['http://a.espncdn.com/i/teamlogos/ncaa/500/21...,5186554.0,20,JJ Rembert,G,70,155,1
1901,1901,Cincinnati,#E00122,#000000,['http://a.espncdn.com/i/teamlogos/ncaa/500/21...,5105811.0,0,Dan Skillings Jr.,G,78,215,3
1902,1902,Cincinnati,#E00122,#000000,['http://a.espncdn.com/i/teamlogos/ncaa/500/21...,5175032.0,1,Day Day Thomas,G,73,190,4

In [101]:
def get_bkb_played_games(team_name, year):
  sched_df = s.get_team_schedule(team_name, year)
  
  sched_df["datetime"] = sched_df.apply(bkbPlayers.to_utc, axis=1)

  now = datetime.now()

  return sched_df.query(f'datetime <= "{now.strftime("%Y-%m-%d")}"')

In [117]:
player_id = 5105811
played_games = get_bkb_played_games('cincinnati', 2025)["game_id"].astype('int').values.tolist()

In [131]:
len(played_games)
stats_df = pd.DataFrame(columns=['player_id', '3pm', '2pm',
                                'ftm', 'reb', 'ast', 'blk', 'stl', 'to'])

for game in played_games:
    curr_game_stats = s.get_game_boxscore(game)[['player_id', '3pm', '2pm',
                                'ftm', 'reb', 'ast', 'blk', 'stl', 'to']]
    
    curr_stats = curr_game_stats.query(f'player_id == "{player_id}"')
    
    if not(curr_stats.empty):
        stats_df.loc[len(stats_df)] = curr_stats.iloc[0]

stats_df

  player_id 3pm 2pm ftm reb ast blk stl to
0   5105811   1   5   4  11   4   1   1  2
1   5105811   0   1   0   3   3   1   1  1
2   5105811   1   3   1   2   2   1   2  1
3   5105811   0   5   5   5   1   1   4  1
4   5105811   1   2   0   4   3   2   0  1
5   5105811   4   3   0   2   1   0   1  2
6   5105811   2   4   4   6   2   1   1  1

In [135]:
stats_df["2pm"].sum()

23

In [137]:
stats_df = pd.DataFrame(columns=['player_id', '3pm', '2pm',
                                'ftm', 'reb', 'ast', 'blk', 'stl', 'to'])
stats_df["2pm"].sum()

0

In [1]:
%pip install selenium

Collecting selenium
  Downloading selenium-4.27.1-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\juan_\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (2.2.2)
Collecting trio~=0.17 (from selenium)
  Downloading trio-0.28.0-py3-none-any.whl.metadata (8.5 kB)
Collecting trio-websocket~=0.9 (from selenium)
  Downloading trio_websocket-0.11.1-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\juan_\anaconda3\lib\site-packages (from selenium) (2024.8.30)
Requirement already satisfied: typing_extensions~=4.9 in c:\users\juan_\anaconda3\lib\site-packages (from selenium) (4.11.0)
Requirement already satisfied: websocket-client~=1.8 in c:\users\juan_\anaconda3\lib\site-packages (from selenium) (1.8.0)
Collecting attrs>=23.2.0 (from trio~=0.17->selenium)
  Downloading attrs-24.3.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: sortedcontainers in c:\users\juan_\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\juan_\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.7)
Collecting outcome (from trio~=0.17->selenium)
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\juan_\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.0)
Requirement already satisfied: cffi>=1.14 in c:\users\juan_\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.16.0)
Collecting wsproto>=0.14 (from trio-websocket~=0.9->selenium)
  Downloading wsproto-1.2.0-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in c:\users\juan_\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\juan_\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\juan_\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)
Downloading selenium-4.27.1-py3-none-any.whl (9.7 MB)
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB 1.3 MB/s eta 0:00:08
   ---------------------------------------- 0.1/9.7 MB 812.7 kB/s eta 0:00:12
    --------------------------------------- 0.1/9.7 MB 1.0 MB/s eta 0:00:10
    --------------------------------------- 0.2/9.7 MB 1.4 MB/s eta 0:00:07
    --------------------------------------- 0.2/9.7 MB 1.4 MB/s eta 0:00:07
   -- ------------------------------------- 0.5/9.7 MB 2.0 MB/s eta 0:00:05
   -- ------------------------------------- 0.5/9.7 MB 2.0 MB/s eta 0:00:05
   -- ------------------------------------- 0.6/9.7 MB 1.7 MB/s eta 0:00:06
   ---- ----------------------------------- 1.0/9.7 MB 2.7 MB/s eta 0:00:04
   ----- ---------------------------------- 1.4/9.7 MB 3.2 MB/s eta 0:00:03
   -------- ------------------------------- 2.1/9.7 MB 4.3 MB/s eta 0:00:02
   ----------- ---------------------------- 2.7/9.7 MB 5.2 MB/s eta 0:00:02
   ---------------- ----------------------- 4.0/9.7 MB 7.0 MB/s eta 0:00:01
   ---------------------- ----------------- 5.4/9.7 MB 8.6 MB/s eta 0:00:01
   --------------------------- ------------ 6.8/9.7 MB 10.1 MB/s eta 0:00:01
   --------------------------------- ------ 8.2/9.7 MB 11.4 MB/s eta 0:00:01
   ---------------------------------------  9.5/9.7 MB 12.4 MB/s eta 0:00:01
   ---------------------------------------  9.5/9.7 MB 12.4 MB/s eta 0:00:01
   ---------------------------------------  9.5/9.7 MB 12.4 MB/s eta 0:00:01
   ---------------------------------------- 9.7/9.7 MB 10.9 MB/s eta 0:00:00
Downloading trio-0.28.0-py3-none-any.whl (486 kB)
   ---------------------------------------- 0.0/486.3 kB ? eta -:--:--
   --------------------------------------- 486.3/486.3 kB 29.8 MB/s eta 0:00:00
Downloading trio_websocket-0.11.1-py3-none-any.whl (17 kB)
Downloading attrs-24.3.0-py3-none-any.whl (63 kB)
   ---------------------------------------- 0.0/63.4 kB ? eta -:--:--
   ---------------------------------------- 63.4/63.4 kB ? eta 0:00:00
Downloading wsproto-1.2.0-py3-none-any.whl (24 kB)
Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Installing collected packages: wsproto, attrs, outcome, trio, trio-websocket, selenium
  Attempting uninstall: attrs
    Found existing installation: attrs 23.1.0
    Uninstalling attrs-23.1.0:
      Successfully uninstalled attrs-23.1.0
Successfully installed attrs-24.3.0 outcome-1.3.0.post0 selenium-4.27.1 trio-0.28.0 trio-websocket-0.11.1 wsproto-1.2.0
Note: you may need to restart the kernel to use updated packages.

In [13]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import Select
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

# Set up the WebDriver (replace 'chromedriver' with the path to your WebDriver)
driver = webdriver.Chrome()

#driver.get("https://www.google.com")

In [3]:
try:
    # Open the NCAA rankings page
    driver.get("https://stats.ncaa.org/rankings/ranking_summary")

    # Wait for the page to load
    wait = WebDriverWait(driver, 10)

    # Select "Baseball" from the sports dropdown
    sports_dropdown = wait.until(EC.presence_of_element_located((By.ID, "sport")))
    Select(sports_dropdown).select_by_visible_text("Baseball")

    wait = WebDriverWait(driver, 10)
    
    # Select "Division I" from the division dropdown
    division_dropdown = wait.until(EC.presence_of_element_located((By.ID, "u_div")))
    Select(division_dropdown).select_by_visible_text("I")

    # Wait for the teams dropdown to load and extract options
    teams_dropdown = wait.until(EC.presence_of_element_located((By.ID, "ranking_summary_form_org_id")))
    teams = [option.text for option in Select(teams_dropdown).options]

    # Print the list of teams
    #print("Teams in Division I Baseball:")
    #for team in teams:
    #    print(team)

finally:
    # Close the browser
    driver.quit()

In [133]:

try:
    # Open the NCAA rankings page
    driver.get("https://stats.ncaa.org/rankings/national_ranking?academic_year=2024.0&division=1.0&ranking_period=108.0&sport_code=MBA&stat_seq=496.0")

    # Wait for the page to load
    wait = WebDriverWait(driver, 10)

    
    # Select "Baseball" from the sports dropdown
    sports_dropdown = wait.until(EC.presence_of_element_located((By.NAME, "rankings_table_length")))
    Select(sports_dropdown).select_by_value("-1")
    team_num = int(Select(sports_dropdown).first_selected_option.text)

    # Wait for the table to load
    wait = WebDriverWait(driver, 10)
    table = wait.until(EC.presence_of_element_located((By.XPATH, "//div[@class='dataTables_scrollBody']//table")))

    # Extract rows from the table
    rows = table.find_elements(By.TAG_NAME, "tr")

    teams = []
   
    print("Team ID and Name:")
    for row_index in range(1,team_num+1):  # Skip the header row
        # Locate the link within the cell containing the team name
        link = rows[row_index].find_element(By.XPATH, f'//*[@id="rankings_table"]/tbody/tr[{row_index}]/td[2]/a')
        team_name = link.text
        team_id = link.get_attribute("href").split("/")[-1]  # Extract the ID from the URL
        teams.append({"id": team_id, "name": team_name})
        row_index = 1 + row_index

    #print(teams)
    print("Scrape Done!")
finally:
    # Close the browser
    driver.quit()

Team ID and Name:
Scrape Done!

In [ ]:
year = datetime.now().year
try:
    for team in teams:
        team["id"] = int(team["id"])
    
        driver = webdriver.Chrome()
    
        # Open the NCAA rankings page
        driver.get(f"https://stats.ncaa.org/teams/{team['id']}")

        year_str = str(int(year) - 1) + '-' + str(year)[-2:]

        wait = WebDriverWait(driver, 10)
        
        # Select "Baseball" from the sports dropdown
        year_dropdown = wait.until(EC.presence_of_element_located((By.ID, "year_list")))
        Select(year_dropdown).select_by_visible_text(year_str)
        
        wait = WebDriverWait(driver, 10)
    
        
        
        if team["name"].find('(') != -1:
            team["conference"] = team["name"][(team["name"].find('(')+1) : team["name"].find(')')]
            team["name"] = team["name"][:(team["name"].find('(')-1)]

        new_url = driver.current_url
        new_number = new_url.split("/")[-1]
        new_number = new_number[:(new_number.find('?'))]

        team["id"] = new_number
        
        driver.quit()  
        
finally:
    # Close the browser
    #driver.quit() 
    pass

teams

In [ ]:
teams

In [144]:
import pandas as pd
import os
teams_df = pd.DataFrame(teams)

In [146]:
teams_df.to_csv(f"{os.getcwd()}/cache/bsb/bsb_teams.csv")

In [115]:
teams_df

        id              name  conference
0    59642         Texas A&M         SEC
1    59664        Oregon St.      Pac-12
2    59667    South Carolina         SEC
3    59672         Tennessee         SEC
4    59642              Troy    Sun Belt
..     ...               ...         ...
289  59651          UC Davis    Big West
290  59648            Alcorn        SWAC
291  59652       The Citadel       SoCon
292  59660  Mississippi Val.        SWAC
293  59652           Cornell  Ivy League

[294 rows x 3 columns]

In [7]:
import pandas as pd
import os
teams_df = pd.read_csv(f"{os.getcwd()}/cache/bsb/bsb_teams.csv")
teams_df

     index      id              name  conference
0        0  596420         Texas A&M         SEC
1        1  596643        Oregon St.      Pac-12
2        2  596677    South Carolina         SEC
3        3  596721         Tennessee         SEC
4        4  596429              Troy    Sun Belt
..     ...     ...               ...         ...
290    290  596483            Alcorn        SWAC
291    291  596522       The Citadel       SoCon
292    292  596606  Mississippi Val.        SWAC
293    293  596528           Cornell  Ivy League
294    294  596556           Harvard  Ivy League

[295 rows x 4 columns]

In [17]:
def findnth(haystack, needle, n):
    parts= haystack.split(needle, n+1)
    if len(parts)<=n+1:
        return -1
    return len(haystack)-len(parts[-1])-len(needle)

In [49]:

team_name = teams_df.iloc[0]['name']
team_id = teams_df.query(f"name == '{team_name}'").iloc[0]['id']
year = 2024
try:
    
        #team["id"] = int(team["id"])
    
        driver = webdriver.Chrome()
    
        # Open the NCAA rankings page
        driver.get(f"https://stats.ncaa.org/teams/{team_id}")

        if year != datetime.now().year: 
            year_str = str(int(year) - 1) + '-' + str(year)[-2:]
    
            wait = WebDriverWait(driver, 10)
            
            # Select "year" from the year dropdown
            year_dropdown = wait.until(EC.presence_of_element_located((By.ID, "year_list")))
            Select(year_dropdown).select_by_visible_text(year_str)

    
        # Wait for the table to load
        wait = WebDriverWait(driver, 10)
        table = wait.until(EC.presence_of_element_located((By.XPATH, "//div[@class='card-body']//table")))
    
        # Extract rows from the table
        rows = table.text.split('\n')

        #rows = table.find_elements(By.XPATH, ".//tbody/tr")
        games = []
       
        for index in range(1,len(rows)):
            row = rows[index]
            
            if row[0] == '@':
                continue
            #print(row)
        
            date = row[:row.rfind('/')+5]
            #print(date)
        
            if row.find('TBA') == -1:
                opp = row[findnth(row,' ',2):].strip()
            else:
                opp = row[(row.find('TBA')+3):].strip()


            if (row != rows[-1]):
                if (rows[index+1][0] == '@'):
                    home = False
                elif opp.find('@') == -1:
                    home = True
                else:
                    home = False
                    opp = opp.replace('@', '').strip()
            else:
                if opp.find('@') == -1:
                    home = True
                else:
                    home = False
                    opp = opp.replace('@', '').strip()

            games.append({"date": date, "opponent": opp, "home": home})
finally:
    # Close the browser
    driver.quit() 
    

games

[{'date': '02/16/2024', 'opponent': '15-0 7,078', 'home': True},
 {'date': '02/17/2024', 'opponent': '6-1 5,818', 'home': True},
 {'date': '02/18/2024', 'opponent': '10-0 5,500', 'home': True},
 {'date': '02/20/2024', 'opponent': '9-3 4,870', 'home': True},
 {'date': '02/23/2024', 'opponent': '17-2 5,944', 'home': True},
 {'date': '02/24/2024', 'opponent': '2-0 6,187', 'home': True},
 {'date': '02/25/2024', 'opponent': '21-2 5,201', 'home': True},
 {'date': '02/27/2024', 'opponent': 'W 13-2 5,161', 'home': True},
 {'date': '03/01/2024', 'opponent': '.', 'home': False},
 {'date': '03/02/2024', 'opponent': 'a', 'home': False},
 {'date': '03/03/2024', 'opponent': '.', 'home': False},
 {'date': '03/05/2024', 'opponent': 'W 9-2 8,060', 'home': True},
 {'date': '03/06/2024', 'opponent': 'W 7-4 4,720', 'home': True},
 {'date': '03/08/2024', 'opponent': 'W 11-0 5,480', 'home': True},
 {'date': '03/09/2024', 'opponent': 'W 6-0 5,964', 'home': True},
 {'date': '03/10/2024', 'opponent': 'W 12-11 (10) 5,857', 'home': True},
 {'date': '03/12/2024', 'opponent': 'W 9-8 7,342', 'home': True},
 {'date': '03/15/2024', 'opponent': 'L 6-8 5,863', 'home': True},
 {'date': '03/16/2024', 'opponent': 'W 10-6 6,541', 'home': True},
 {'date': '03/17/2024', 'opponent': 'L 2-4 6,110', 'home': True},
 {'date': '03/20/2024', 'opponent': 'W 11-9 4,547', 'home': True},
 {'date': '03/21/2024', 'opponent': 'W 6-3 4,776', 'home': True},
 {'date': '03/22/2024', 'opponent': 'L 1-5 6,443', 'home': True},
 {'date': '03/23/2024', 'opponent': 'W 6-1 7,159', 'home': True},
 {'date': '03/26/2024', 'opponent': 'W 6-3 4,784', 'home': True},
 {'date': '03/28/2024', 'opponent': '9-7 6,466', 'home': True},
 {'date': '03/29/2024', 'opponent': '12-8 6,664', 'home': True},
 {'date': '03/30/2024', 'opponent': '10-9 (12) 6,484', 'home': True},
 {'date': '04/02/2024', 'opponent': 'St. W 12-2 2,917', 'home': True},
 {'date': '04/05/2024', 'opponent': 'Carolina W 9-2 7,159', 'home': True},
 {'date': '04/06/2024', 'opponent': 'Carolina W 6-3 8,242', 'home': True},
 {'date': '04/07/2024', 'opponent': 'Carolina L 5-6 6,720', 'home': True},
 {'date': '04/09/2024', 'opponent': '6-5 4,826', 'home': True},
 {'date': '04/12/2024', 'opponent': '15-0 7,351', 'home': True},
 {'date': '04/13/2024', 'opponent': '9-0 8,075', 'home': True},
 {'date': '04/14/2024', 'opponent': '12-6 7,063', 'home': True},
 {'date': '04/16/2024', 'opponent': 'W 15-5 5,407', 'home': True},
 {'date': '04/19/2024', 'opponent': 'W 10-5 0', 'home': True},
 {'date': '04/19/2024', 'opponent': 'W 18-9 3,691', 'home': True},
 {'date': '04/20/2024', 'opponent': 'L 9-10 3,995', 'home': True},
 {'date': '04/23/2024', 'opponent': '13-11 6,248', 'home': True},
 {'date': '04/26/2024', 'opponent': '5-2 7,968', 'home': True},
 {'date': '04/27/2024', 'opponent': '19-9 7,770', 'home': True},
 {'date': '04/27/2024', 'opponent': '4-5 7,021', 'home': True},
 {'date': '04/30/2024', 'opponent': 'W 10-6 5,919', 'home': True},
 {'date': '05/03/2024', 'opponent': 'L 4-6 11,007', 'home': True},
 {'date': '05/04/2024', 'opponent': 'L 4-6 11,751', 'home': True},
 {'date': '05/05/2024', 'opponent': 'W 14-4 10,747', 'home': True},
 {'date': '05/07/2024', 'opponent': '16-3 7,111', 'home': True},
 {'date': '05/10/2024', 'opponent': 'Miss L 3-4 9,155', 'home': True},
 {'date': '05/11/2024', 'opponent': 'Miss L 2-10 9,310', 'home': True},
 {'date': '05/12/2024', 'opponent': 'Miss W 6-0 9,013', 'home': True},
 {'date': '05/16/2024', 'opponent': '1-0 (11) 6,976', 'home': True},
 {'date': '05/17/2024', 'opponent': '3-6 7,980', 'home': True},
 {'date': '05/18/2024', 'opponent': '14-4 7,337', 'home': True},
 {'date': '05/22/2024', 'opponent': 'St.', 'home': False},
 {'date': '05/23/2024', 'opponent': 'e', 'home': False},
 {'date': '05/31/2024', 'opponent': 'g', 'home': True},
 {'date': '2024', 'opponent': 'Championship W 8-0 7,034', 'home': True},
 {'date': '06/01/2024', 'opponent': 's', 'home': True},
 {'date': '2024', 'opponent': 'Championship W 4-2 (11) 7,630', 'home': True},
 {'date': '06/02/2024', 'opponent': 'a', 'home': True},
 {'date': '2024', 'opponent': 'Championship W 9-4 7,328', 'home': True},
 {'date': '06/08/2024', 'opponent': 'n', 'home': True},
 {'date': '2024', 'opponent': 'Championship W 10-6 7,835', 'home': True},
 {'date': '06/09/2024', 'opponent': 'n', 'home': True},
 {'date': '2024', 'opponent': 'Championship W 15-9 7,934', 'home': True},
 {'date': '06/15/2024', 'opponent': 'a', 'home': False},
 {'date': '06/17/2024', 'opponent': 'y', 'home': False},
 {'date': '06/19/2024', 'opponent': 'a', 'home': False},
 {'date': '06/22/2024', 'opponent': 'e', 'home': False},
 {'date': '06/23/2024', 'opponent': 'e', 'home': False},
 {'date': '06/24/2024', 'opponent': 'e', 'home': False}]

In [185]:

team_name = 'UNLV'
team_id = teams_df.query(f"name == '{team_name}'").iloc[0]['id']
year = 2025
try:
    
        #team["id"] = int(team["id"])
    
        driver = webdriver.Chrome()
    
        # Open the NCAA rankings page
        driver.get(f"https://stats.ncaa.org/teams/{team_id}")

        if year != datetime.now().year: 
            year_str = str(int(year) - 1) + '-' + str(year)[-2:]
    
            wait = WebDriverWait(driver, 10)
            
            # Select "year" from the year dropdown
            year_dropdown = wait.until(EC.presence_of_element_located((By.ID, "year_list")))
            Select(year_dropdown).select_by_visible_text(year_str)

    
        # Wait for the table to load
        wait = WebDriverWait(driver, 10)
        table = wait.until(EC.presence_of_element_located((By.XPATH, "//div[@class='card-body']//table")))
    
        # Extract rows from the table
        rows = table.text.split('\n')

        #rows = table.find_elements(By.XPATH, ".//tbody/tr")
        games = []
       
        for index in range(1,len(rows)):
            row = rows[index]
            
            if row[0] == '@':
                continue
            
            if row[0:4] == str(year):
                continue
        
            date = row[:row.rfind('/')+5]
            date_list = date.split('/')
            #print(f'{date=}')
    
            year = date_list[2]
            year_format = year[-2:]
            year_format

            #print(f'{date_list=}')
            #print(f'{year=}')
            
            date_format = date[:date.rfind('/')+1]
            #print(f'{date_format=}')
            datetime_str = date_format + year_format + ' 00:00:00'
            
            game_date = datetime.strptime(datetime_str, '%m/%d/%y %H:%M:%S')

            if game_date <= datetime.now():
                    last_W = row.rfind('W')
                    last_L = row.rfind('L')
                
                    if last_W == -1:
                        result_index = last_L
                    elif last_L == -1:
                        result_index = last_W
                    elif last_W > last_L:
                        result_index = last_W
                    else:
                        result_index = last_L
                
                    if result_index != -1:
                        opp = row[row.find(date)+len(date):result_index].strip()
                    else:
                        opp = row[row.find(date)+len(date):].strip()
                
                    if (opp.find(')') != -1) and (opp.find('(OH)') == -1):
                        opp = opp[opp.find(')')+1:].strip()
                
                    if opp.find('#') != -1:
                        opp = row[row.find('#')+3:].strip()
                
                    if (row != rows[-1]):
                        if (rows[index+1][0] == '@') or (rows[index+1][0:4] == str(year)):
                            home = False
                        elif opp.find('@') == -1:
                            home = True
                        else:
                            home = False
                            opp = opp.replace('@', '').strip()
                    else:
                        if opp.find('@') == -1:
                            home = True
                        else:
                            home = False
                            opp = opp.replace('@', '').strip()
            else:
                if row.find('TBA') == -1:
                    opp = row[findnth(row,' ',2):].strip()
                else:
                    opp = row[(row.find('TBA')+3):].strip()
    
    
                if (row != rows[-1]):
                    if (rows[index+1][0] == '@'):
                        home = False
                    elif opp.find('@') == -1:
                        home = True
                    else:
                        home = False
                        opp = opp.replace('@', '').strip()
                else:
                    if opp.find('@') == -1:
                        home = True
                    else:
                        home = False
                        opp = opp.replace('@', '').strip()
            
            opp = opp.replace('Canceled', '').strip()
                
            games.append({"date": str(game_date), "opponent": opp, "home": home})
finally:
    # Close the browser
    driver.quit() 
    

games

[{'date': '2025-02-14 00:00:00', 'opponent': 'Indiana', 'home': False},
 {'date': '2025-02-17 00:00:00', 'opponent': 'Indiana', 'home': False},
 {'date': '2025-02-21 00:00:00', 'opponent': 'Cincinnati', 'home': True},
 {'date': '2025-02-22 00:00:00', 'opponent': 'Cincinnati', 'home': True},
 {'date': '2025-02-23 00:00:00', 'opponent': 'Cincinnati', 'home': True},
 {'date': '2025-02-24 00:00:00', 'opponent': 'Cincinnati', 'home': True},
 {'date': '2025-02-28 00:00:00', 'opponent': 'Milwaukee', 'home': True},
 {'date': '2025-03-01 00:00:00', 'opponent': 'Milwaukee', 'home': True},
 {'date': '2025-03-01 00:00:00', 'opponent': 'Milwaukee', 'home': True},
 {'date': '2025-03-02 00:00:00', 'opponent': 'Milwaukee', 'home': True},
 {'date': '2025-03-07 00:00:00', 'opponent': "Saint Mary's", 'home': False},
 {'date': '2025-03-21 00:00:00', 'opponent': 'Fresno St.', 'home': True},
 {'date': '2025-03-22 00:00:00', 'opponent': 'Fresno St.', 'home': True},
 {'date': '2025-03-23 00:00:00', 'opponent': 'Fresno St.', 'home': True},
 {'date': '2025-03-28 00:00:00', 'opponent': 'San Diego St.', 'home': False},
 {'date': '2025-03-29 00:00:00', 'opponent': 'San Diego St.', 'home': False},
 {'date': '2025-03-30 00:00:00', 'opponent': 'San Diego St.', 'home': False},
 {'date': '2025-03-31 00:00:00',
  'opponent': 'California Baptist',
  'home': False},
 {'date': '2025-04-04 00:00:00', 'opponent': 'Nevada', 'home': True},
 {'date': '2025-04-05 00:00:00', 'opponent': 'Nevada', 'home': True},
 {'date': '2025-04-06 00:00:00', 'opponent': 'Nevada', 'home': True},
 {'date': '2025-04-07 00:00:00', 'opponent': 'Utah Valley', 'home': True},
 {'date': '2025-04-08 00:00:00', 'opponent': 'Utah Valley', 'home': True},
 {'date': '2025-04-11 00:00:00', 'opponent': 'Air Force', 'home': False},
 {'date': '2025-04-12 00:00:00', 'opponent': 'Air Force', 'home': False},
 {'date': '2025-04-13 00:00:00', 'opponent': 'Air Force', 'home': False},
 {'date': '2025-04-25 00:00:00', 'opponent': 'San Diego St.', 'home': True},
 {'date': '2025-04-26 00:00:00', 'opponent': 'San Diego St.', 'home': True},
 {'date': '2025-04-27 00:00:00', 'opponent': 'San Diego St.', 'home': True},
 {'date': '2025-05-02 00:00:00', 'opponent': 'San Jose St.', 'home': False},
 {'date': '2025-05-03 00:00:00', 'opponent': 'San Jose St.', 'home': False},
 {'date': '2025-05-04 00:00:00', 'opponent': 'San Jose St.', 'home': False},
 {'date': '2025-05-15 00:00:00', 'opponent': 'Air Force', 'home': True},
 {'date': '2025-05-16 00:00:00', 'opponent': 'Air Force', 'home': True},
 {'date': '2025-05-17 00:00:00', 'opponent': 'Air Force', 'home': True}]

In [103]:
row[0:4]

'2024'

In [69]:
raw_date

test = 'ah\'hah'

'05/04/2025'

In [203]:
return_list = []



for index in range(0,len(games)):

    if games[index]['home'] == True:
        home_id = team_id
        home_team = team_name
        away_team = games[index]['opponent']
    else:
        opp_q = teams_df.query(f'name == "{games[index]['opponent']}"')

        if (opp_q.empty):
             opp_id = -1
        else:
             opp_id = opp_q.iloc[0]['id']
        home_id = opp_id
        home_team = games[index]['opponent']
        away_team = team_name
    
    curr_game = fbGame(game_id=game_id,home_id=home_id,
                       away_team=away_team,home_team=home_team,start_date=games[index]['date'])

    return_list.append(curr_game)


for game in return_list:
    print(game)

game_id=596420-1 home_id=596566 home_team=Indiana away_team=UNLV start_date=2025-02-14 00:00:00
game_id=596420-1 home_id=596566 home_team=Indiana away_team=UNLV start_date=2025-02-17 00:00:00
game_id=596420-1 home_id=596619 home_team=UNLV away_team=Cincinnati start_date=2025-02-21 00:00:00
game_id=596420-1 home_id=596619 home_team=UNLV away_team=Cincinnati start_date=2025-02-22 00:00:00
game_id=596420-1 home_id=596619 home_team=UNLV away_team=Cincinnati start_date=2025-02-23 00:00:00
game_id=596420-1 home_id=596619 home_team=UNLV away_team=Cincinnati start_date=2025-02-24 00:00:00
game_id=596420-1 home_id=596619 home_team=UNLV away_team=Milwaukee start_date=2025-02-28 00:00:00
game_id=596420-1 home_id=596619 home_team=UNLV away_team=Milwaukee start_date=2025-03-01 00:00:00
game_id=596420-1 home_id=596619 home_team=UNLV away_team=Milwaukee start_date=2025-03-01 00:00:00
game_id=596420-1 home_id=596619 home_team=UNLV away_team=Milwaukee start_date=2025-03-02 00:00:00
game_id=596420-1 home_id=596665 home_team=Saint Mary's away_team=UNLV start_date=2025-03-07 00:00:00
game_id=596420-1 home_id=596619 home_team=UNLV away_team=Fresno St. start_date=2025-03-21 00:00:00
game_id=596420-1 home_id=596619 home_team=UNLV away_team=Fresno St. start_date=2025-03-22 00:00:00
game_id=596420-1 home_id=596619 home_team=UNLV away_team=Fresno St. start_date=2025-03-23 00:00:00
game_id=596420-1 home_id=596669 home_team=San Diego St. away_team=UNLV start_date=2025-03-28 00:00:00
game_id=596420-1 home_id=596669 home_team=San Diego St. away_team=UNLV start_date=2025-03-29 00:00:00
game_id=596420-1 home_id=596669 home_team=San Diego St. away_team=UNLV start_date=2025-03-30 00:00:00
game_id=596420-1 home_id=596476 home_team=California Baptist away_team=UNLV start_date=2025-03-31 00:00:00
game_id=596420-1 home_id=596619 home_team=UNLV away_team=Nevada start_date=2025-04-04 00:00:00
game_id=596420-1 home_id=596619 home_team=UNLV away_team=Nevada start_date=2025-04-05 00:00:00
game_id=596420-1 home_id=596619 home_team=UNLV away_team=Nevada start_date=2025-04-06 00:00:00
game_id=596420-1 home_id=596619 home_team=UNLV away_team=Utah Valley start_date=2025-04-07 00:00:00
game_id=596420-1 home_id=596619 home_team=UNLV away_team=Utah Valley start_date=2025-04-08 00:00:00
game_id=596420-1 home_id=596430 home_team=Air Force away_team=UNLV start_date=2025-04-11 00:00:00
game_id=596420-1 home_id=596430 home_team=Air Force away_team=UNLV start_date=2025-04-12 00:00:00
game_id=596420-1 home_id=596430 home_team=Air Force away_team=UNLV start_date=2025-04-13 00:00:00
game_id=596420-1 home_id=596619 home_team=UNLV away_team=San Diego St. start_date=2025-04-25 00:00:00
game_id=596420-1 home_id=596619 home_team=UNLV away_team=San Diego St. start_date=2025-04-26 00:00:00
game_id=596420-1 home_id=596619 home_team=UNLV away_team=San Diego St. start_date=2025-04-27 00:00:00
game_id=596420-1 home_id=596672 home_team=San Jose St. away_team=UNLV start_date=2025-05-02 00:00:00
game_id=596420-1 home_id=596672 home_team=San Jose St. away_team=UNLV start_date=2025-05-03 00:00:00
game_id=596420-1 home_id=596672 home_team=San Jose St. away_team=UNLV start_date=2025-05-04 00:00:00
game_id=596420-1 home_id=596619 home_team=UNLV away_team=Air Force start_date=2025-05-15 00:00:00
game_id=596420-1 home_id=596619 home_team=UNLV away_team=Air Force start_date=2025-05-16 00:00:00
game_id=596420-1 home_id=596619 home_team=UNLV away_team=Air Force start_date=2025-05-17 00:00:00

In [201]:
games[index]
games[index]['opponent'].replace("'", "\"")

'Saint Mary"s'

In [51]:
rows

['Date Opponent Result Attendance',
 '02/16/2024 McNeese W 15-0 7,078',
 '02/17/2024 McNeese W 6-1 5,818',
 '02/18/2024 McNeese W 10-0 5,500',
 '02/20/2024 UIW W 9-3 4,870',
 '02/23/2024 Wagner W 17-2 5,944',
 '02/24/2024 Wagner W 2-0 6,187',
 '02/25/2024 Wagner W 21-2 5,201',
 '02/27/2024 Lamar University W 13-2 5,161',
 '03/01/2024 Arizona St.',
 '@Arlington, TX W 4-0 7,273',
 '03/02/2024 Southern California',
 '@Arlington, TX W 9-3 10,547',
 '03/03/2024 Arizona St.',
 '@Arlington, TX W 10-5 6,516',
 '03/05/2024 @ Texas W 9-2 8,060',
 '03/06/2024 Texas Southern W 7-4 4,720',
 '03/08/2024 Rhode Island W 11-0 5,480',
 '03/09/2024 Rhode Island W 6-0 5,964',
 '03/10/2024 Rhode Island W 12-11 (10) 5,857',
 '03/12/2024 Sam Houston W 9-8 7,342',
 '03/15/2024 @ Florida L 6-8 5,863',
 '03/16/2024 @ Florida W 10-6 6,541',
 '03/17/2024 @ Florida L 2-4 6,110',
 '03/20/2024 Prairie View W 11-9 4,547',
 '03/21/2024 Mississippi St. W 6-3 4,776',
 '03/22/2024 Mississippi St. L 1-5 6,443',
 '03/23/2024 Mississippi St. W 6-1 7,159',
 '03/26/2024 Houston Christian W 6-3 4,784',
 '03/28/2024 Auburn W 9-7 6,466',
 '03/29/2024 Auburn W 12-8 6,664',
 '03/30/2024 Auburn W 10-9 (12) 6,484',
 '04/02/2024 @ Texas St. W 12-2 2,917',
 '04/05/2024 @ South Carolina W 9-2 7,159',
 '04/06/2024 @ South Carolina W 6-3 8,242',
 '04/07/2024 @ South Carolina L 5-6 6,720',
 '04/09/2024 UTSA W 6-5 4,826',
 '04/12/2024 Vanderbilt W 15-0 7,351',
 '04/13/2024 Vanderbilt W 9-0 8,075',
 '04/14/2024 Vanderbilt W 12-6 7,063',
 '04/16/2024 Air Force W 15-5 5,407',
 '04/19/2024(1) @ Alabama W 10-5 0',
 '04/19/2024(2) @ Alabama W 18-9 3,691',
 '04/20/2024 @ Alabama L 9-10 3,995',
 '04/23/2024 Houston W 13-11 6,248',
 '04/26/2024 Georgia W 5-2 7,968',
 '04/27/2024(1) Georgia W 19-9 7,770',
 '04/27/2024(2) Georgia L 4-5 7,021',
 '04/30/2024 Tarleton St. W 10-6 5,919',
 '05/03/2024 @ LSU L 4-6 11,007',
 '05/04/2024 @ LSU L 4-6 11,751',
 '05/05/2024 @ LSU W 14-4 10,747',
 '05/07/2024 Rice W 16-3 7,111',
 '05/10/2024 @ Ole Miss L 3-4 9,155',
 '05/11/2024 @ Ole Miss L 2-10 9,310',
 '05/12/2024 @ Ole Miss W 6-0 9,013',
 '05/16/2024 Arkansas W 1-0 (11) 6,976',
 '05/17/2024 Arkansas L 3-6 7,980',
 '05/18/2024 Arkansas W 14-4 7,337',
 '05/22/2024 #5 Mississippi St.',
 '@Hoover, AL (2024 SEC Baseball Championship) L 3-5 11,840',
 '05/23/2024 #1 Tennessee',
 '@Hoover, AL (2024 SEC Baseball Championship) L 4-7 6,825',
 '05/31/2024 #4 Grambling',
 '2024 NCAA Baseball Championship W 8-0 7,034',
 '06/01/2024 #3 Texas',
 '2024 NCAA Baseball Championship W 4-2 (11) 7,630',
 '06/02/2024 #2 Louisiana',
 '2024 NCAA Baseball Championship W 9-4 7,328',
 '06/08/2024 #3 Oregon',
 '2024 NCAA Baseball Championship W 10-6 7,835',
 '06/09/2024 #3 Oregon',
 '2024 NCAA Baseball Championship W 15-9 7,934',
 '06/15/2024 #3 Florida',
 '@Omaha, NE (2024 NCAA Baseball Championship) W 3-2 25,774',
 '06/17/2024 #1 Kentucky',
 '@Omaha, NE (2024 NCAA Baseball Championship) W 5-1 25,327',
 '06/19/2024 #3 Florida',
 '@Omaha, NE (2024 NCAA Baseball Championship) W 6-0 25,429',
 '06/22/2024 #1 Tennessee',
 '@Omaha, NE (2024 NCAA Baseball Championship) W 9-5 26,498',
 '06/23/2024 #1 Tennessee',
 '@Omaha, NE (2024 NCAA Baseball Championship) L 1-4 25,987',
 '06/24/2024 #1 Tennessee',
 '@Omaha, NE (2024 NCAA Baseball Championship) L 5-6 24,685']

In [35]:

team_id
#chosen_id =

596420

In [357]:
datetime_str = '09/19/22 13:55:26'

datetime_object = datetime.strptime(datetime_str, '%m/%d/%y %H:%M:%S')

print(type(datetime_object))
print(datetime_object)  # printed in default format

<class 'datetime.datetime'>
2022-09-19 13:55:26

In [379]:
str(datetime_object)

'2022-09-19 13:55:26'

In [291]:
driver.quit()

In [159]:

for index in range(1,len(rows)):
    row = rows[index]
    
    if row[0] == '@':
        continue
    if row[0:4] == str(year):
                continue
    print(row)

    date = row[:row.rfind('/')+5]
    print(date)

    last_W = row.rfind('W')
    last_L = row.rfind('L')

    if last_W == -1:
        result_index = last_L
    elif last_L == -1:
        result_index = last_W
    elif last_W > last_L:
        result_index = last_W
    else:
        result_index = last_L

    if result_index != -1:
        opp = row[row.find(date)+len(date):result_index].strip()
    else:
        opp = row[row.find(date)+len(date):].strip()

    if opp.find(')') != -1:
        opp = opp[opp.find(')')+1:].strip()

    if opp.find('#') != -1:
        opp = row[row.find('#')+3:].strip()

    if (row != rows[-1]):
        if (rows[index+1][0] == '@') or (rows[index+1][0:4] == str(year)):
            home = False
        elif opp.find('@') == -1:
            home = True
        else:
            home = False
            opp = opp.replace('@', '').strip()
    else:
        if opp.find('@') == -1:
            home = True
        else:
            home = False
            opp = opp.replace('@', '').strip()
    
    
    print(f'{opp=}')
    print(f'{home=}')
    print('----------')
    #break

    #if row !=

02/16/2024 McNeese W 15-0 7,078
02/16/2024
opp='McNeese'
home=True
----------
02/17/2024 McNeese W 6-1 5,818
02/17/2024
opp='McNeese'
home=True
----------
02/18/2024 McNeese W 10-0 5,500
02/18/2024
opp='McNeese'
home=True
----------
02/20/2024 UIW W 9-3 4,870
02/20/2024
opp='UIW'
home=True
----------
02/23/2024 Wagner W 17-2 5,944
02/23/2024
opp='Wagner'
home=True
----------
02/24/2024 Wagner W 2-0 6,187
02/24/2024
opp='Wagner'
home=True
----------
02/25/2024 Wagner W 21-2 5,201
02/25/2024
opp='Wagner'
home=True
----------
02/27/2024 Lamar University W 13-2 5,161
02/27/2024
opp='Lamar University'
home=True
----------
03/01/2024 Arizona St.
03/01/2024
opp='Arizona St.'
home=False
----------
03/02/2024 Southern California
03/02/2024
opp='Southern California'
home=False
----------
03/03/2024 Arizona St.
03/03/2024
opp='Arizona St.'
home=False
----------
03/05/2024 @ Texas W 9-2 8,060
03/05/2024
opp='Texas'
home=False
----------
03/06/2024 Texas Southern W 7-4 4,720
03/06/2024
opp='Texas Southern'
home=True
----------
03/08/2024 Rhode Island W 11-0 5,480
03/08/2024
opp='Rhode Island'
home=True
----------
03/09/2024 Rhode Island W 6-0 5,964
03/09/2024
opp='Rhode Island'
home=True
----------
03/10/2024 Rhode Island W 12-11 (10) 5,857
03/10/2024
opp='Rhode Island'
home=True
----------
03/12/2024 Sam Houston W 9-8 7,342
03/12/2024
opp='Sam Houston'
home=True
----------
03/15/2024 @ Florida L 6-8 5,863
03/15/2024
opp='Florida'
home=False
----------
03/16/2024 @ Florida W 10-6 6,541
03/16/2024
opp='Florida'
home=False
----------
03/17/2024 @ Florida L 2-4 6,110
03/17/2024
opp='Florida'
home=False
----------
03/20/2024 Prairie View W 11-9 4,547
03/20/2024
opp='Prairie View'
home=True
----------
03/21/2024 Mississippi St. W 6-3 4,776
03/21/2024
opp='Mississippi St.'
home=True
----------
03/22/2024 Mississippi St. L 1-5 6,443
03/22/2024
opp='Mississippi St.'
home=True
----------
03/23/2024 Mississippi St. W 6-1 7,159
03/23/2024
opp='Mississippi St.'
home=True
----------
03/26/2024 Houston Christian W 6-3 4,784
03/26/2024
opp='Houston Christian'
home=True
----------
03/28/2024 Auburn W 9-7 6,466
03/28/2024
opp='Auburn'
home=True
----------
03/29/2024 Auburn W 12-8 6,664
03/29/2024
opp='Auburn'
home=True
----------
03/30/2024 Auburn W 10-9 (12) 6,484
03/30/2024
opp='Auburn'
home=True
----------
04/02/2024 @ Texas St. W 12-2 2,917
04/02/2024
opp='Texas St.'
home=False
----------
04/05/2024 @ South Carolina W 9-2 7,159
04/05/2024
opp='South Carolina'
home=False
----------
04/06/2024 @ South Carolina W 6-3 8,242
04/06/2024
opp='South Carolina'
home=False
----------
04/07/2024 @ South Carolina L 5-6 6,720
04/07/2024
opp='South Carolina'
home=False
----------
04/09/2024 UTSA W 6-5 4,826
04/09/2024
opp='UTSA'
home=True
----------
04/12/2024 Vanderbilt W 15-0 7,351
04/12/2024
opp='Vanderbilt'
home=True
----------
04/13/2024 Vanderbilt W 9-0 8,075
04/13/2024
opp='Vanderbilt'
home=True
----------
04/14/2024 Vanderbilt W 12-6 7,063
04/14/2024
opp='Vanderbilt'
home=True
----------
04/16/2024 Air Force W 15-5 5,407
04/16/2024
opp='Air Force'
home=True
----------
04/19/2024(1) @ Alabama W 10-5 0
04/19/2024
opp='Alabama'
home=False
----------
04/19/2024(2) @ Alabama W 18-9 3,691
04/19/2024
opp='Alabama'
home=False
----------
04/20/2024 @ Alabama L 9-10 3,995
04/20/2024
opp='Alabama'
home=False
----------
04/23/2024 Houston W 13-11 6,248
04/23/2024
opp='Houston'
home=True
----------
04/26/2024 Georgia W 5-2 7,968
04/26/2024
opp='Georgia'
home=True
----------
04/27/2024(1) Georgia W 19-9 7,770
04/27/2024
opp='Georgia'
home=True
----------
04/27/2024(2) Georgia L 4-5 7,021
04/27/2024
opp='Georgia'
home=True
----------
04/30/2024 Tarleton St. W 10-6 5,919
04/30/2024
opp='Tarleton St.'
home=True
----------
05/03/2024 @ LSU L 4-6 11,007
05/03/2024
opp='LSU'
home=False
----------
05/04/2024 @ LSU L 4-6 11,751
05/04/2024
opp='LSU'
home=False
----------
05/05/2024 @ LSU W 14-4 10,747
05/05/2024
opp='LSU'
home=False
----------
05/07/2024 Rice W 16-3 7,111
05/07/2024
opp='Rice'
home=True
----------
05/10/2024 @ Ole Miss L 3-4 9,155
05/10/2024
opp='Ole Miss'
home=False
----------
05/11/2024 @ Ole Miss L 2-10 9,310
05/11/2024
opp='Ole Miss'
home=False
----------
05/12/2024 @ Ole Miss W 6-0 9,013
05/12/2024
opp='Ole Miss'
home=False
----------
05/16/2024 Arkansas W 1-0 (11) 6,976
05/16/2024
opp='Arkansas'
home=True
----------
05/17/2024 Arkansas L 3-6 7,980
05/17/2024
opp='Arkansas'
home=True
----------
05/18/2024 Arkansas W 14-4 7,337
05/18/2024
opp='Arkansas'
home=True
----------
05/22/2024 #5 Mississippi St.
05/22/2024
opp='Mississippi St.'
home=False
----------
05/23/2024 #1 Tennessee
05/23/2024
opp='Tennessee'
home=False
----------
05/31/2024 #4 Grambling
05/31/2024
opp='Grambling'
home=False
----------
06/01/2024 #3 Texas
06/01/2024
opp='Texas'
home=False
----------
06/02/2024 #2 Louisiana
06/02/2024
opp='Louisiana'
home=False
----------
06/08/2024 #3 Oregon
06/08/2024
opp='Oregon'
home=False
----------
06/09/2024 #3 Oregon
06/09/2024
opp='Oregon'
home=False
----------
06/15/2024 #3 Florida
06/15/2024
opp='Florida'
home=False
----------
06/17/2024 #1 Kentucky
06/17/2024
opp='Kentucky'
home=False
----------
06/19/2024 #3 Florida
06/19/2024
opp='Florida'
home=False
----------
06/22/2024 #1 Tennessee
06/22/2024
opp='Tennessee'
home=False
----------
06/23/2024 #1 Tennessee
06/23/2024
opp='Tennessee'
home=False
----------
06/24/2024 #1 Tennessee
06/24/2024
opp='Tennessee'
home=False
----------

In [125]:
row.find(date)
#date
#row

0

In [309]:
row

'05/11/2025 02:05 PM Iowa'

In [299]:
index

24

In [311]:
len(rows)

29